vars:
  - params.yaml

stages:
  generate:
    cmd: >-
      rm -rf synthea-runner/output/synthea_raw &&
      docker build -t synthea synthea-runner/synthea-docker/ &&
      docker run --rm
      -e JAVA_OPTS=-Xmx8g
      -v $(pwd)/synthea-runner/output/synthea_raw:/synthea/synthea/output
      synthea
      /bin/sh -c "./run_synthea -p ${generate.population} -s ${generate.seed}
      --exporter.baseDirectory=./output --exporter.csv.export=true
      --exporter.fhir.export=false Massachusetts"
    params:
      - generate.population
      - generate.seed
    deps:
      - synthea-runner/synthea-docker/Dockerfile
    outs:
      - synthea-runner/output/synthea_raw/csv:
          cache: false

  augment:
    cmd: >-
      rm -rf output/augmented &&
      docker build -t augmentation augmentation/ &&
      docker run --rm
      -v $(pwd)/synthea-runner/output/synthea_raw/csv:/data/input:ro
      -v $(pwd)/output/augmented:/data/output
      augmentation
      --input /data/input
      --output /data/output
      --random-seed ${augment.random_seed}
    params:
      - augment.random_seed
    deps:
      - synthea-runner/output/synthea_raw/csv
      - augmentation/Dockerfile
      - augmentation/requirements-runtime.txt
      - augmentation/cli/augment.py
      - augmentation/config/default_config.yaml
    outs:
      - output/augmented:
          cache: false

  infer:
    cmd: >-
      rm -rf output/inferred &&
      mkdir -p output/inferred &&
      fine-tuning/infer_remote.sh
      output/resolved/gray_zone_pairs.csv
      output/inferred/predictions.csv
    deps:
      - fine-tuning/Dockerfile
      - fine-tuning/infer_remote.sh
      - fine-tuning/inference_classifier.py
      - fine-tuning/requirements.txt
      - fine-tuning/run_on_runpod.sh
      - output/resolved/gray_zone_pairs.csv
    outs:
      - output/inferred/predictions.csv:
          cache: false
