generate:
  population: 500
  seed: 67890

augment:
  assignment_seed: 99
  error_seed: 99

resolve:
  auto_match_probability: 0.95
  auto_reject_probability: 0.05

generate_training:
  population: 100000
  seed: 12345

augment_training:
  assignment_seed: 42
  error_seed: 42

prepare_dataset:
  seed: 42

train:
  epochs: 3
  batch_size: 4
  lr: 0.0001
  max_length: 2048
  lora_r: 16
