generate:
  population: 5000
  seed: 67890

augment:
  assignment_seed: 99
  error_seed: 99
  confusable_pct: 5.0
  min_errors: 8
  max_errors: 12
  error_weights: '{"name_variation":0.35,"address_error":0.05,"date_variation":0.15,"ssn_error":0.15,"formatting_error":0.00,"missing_data":0.30}'

resolve:
  auto_match_probability: 0.99
  auto_reject_probability: 0.01

generate_training:
  population: 30000
  seed: 12345

augment_training:
  assignment_seed: 42
  error_seed: 42
  confusable_pct: 5.0
  min_errors: 3
  max_errors: 5
  error_weights: '{"name_variation":0.30,"address_error":0.20,"date_variation":0.15,"ssn_error":0.05,"formatting_error":0.00,"missing_data":0.30}'

prepare_dataset:
  seed: 42

train:
  epochs: 3
  batch_size: 4
  grad_accum: 8
  lr: 0.0001
  max_length: 2048
  lora_r: 16
  max_samples: 0
  max_steps: 5000
