generate:
  population: 10000
  seed: 67890

augment:
  assignment_seed: 99
  error_seed: 99
  confusable_pairs: 500

resolve:
  auto_match_probability: 0.95
  auto_reject_probability: 0.05

generate_training:
  population: 30000
  seed: 12345

augment_training:
  assignment_seed: 42
  error_seed: 42
  confusable_pairs: 500

prepare_dataset:
  seed: 42

train:
  epochs: 3
  batch_size: 8
  lr: 0.0001
  max_length: 2048
  lora_r: 16
  max_samples: 0
